### ISSUE TITLE
Working with CAPACITOR JS

### ISSUE THREAD

**Issue by alanxp** [zdenham/next-static-utils#3] opened 2024-06-23 07:05 UTC
Got it working, however when using cpaacitor js where we use the exported "out" directory into webview, i ran into this error in xcode

 [error] - Failed to fetch RSC payload for capacitor://localhost/admin/regions/65d2cd8d281b553da132e9be.

![image](https://github.com/zdenham/next-static-utils/assets/15839818/ea6e8827-5127-41df-95c8-fa41182f9caa)

**Comment by zdenham** [comment] 2024-06-24 05:37
Are you able to isolate this issue to something with `next-static-utils`? I'm not very familiar with capacitor, but would like to understand your use case a bit more

**Comment by alanxp** [comment] 2024-06-24 12:20
> Are you able to isolate this issue to something with `next-static-utils`? I'm not very familiar with capacitor, but would like to understand your use case a bit more

![image](https://github.com/zdenham/next-static-utils/assets/15839818/357b18fb-bcb5-4264-b4cf-15981c4413a4)

I believe because it is expecting to have the page 65d2cd8d..html

The use case is simply export all static html site into a webview that capacitor has to show it as an "app" for android/ios. All it needs is the static html for it to work.

I can do it with Sveltekit Static Export, but can't seem to get it with Next.JS

**Comment by zdenham** [comment] 2024-06-25 05:28
Are you using the `useDynamicParams` hook? or getStaticParams on your pages? We don't support using getStaticParams. Not sure I can help without more information unfortunately. If you are able to share a repo / steps to reproduce I can look into it

**Comment by alanxp** [comment] 2024-06-25 05:32
> Are you using the `useDynamicParams` hook? or getStaticParams on your pages? We don't support using getStaticParams

App Router... using useDynamicParams ofc. 
What capacitor does is if the link is a href="/regions/randomObjectIdHere123.html" it expects a randomObjectIdHere123.html, it could "simulate" the route next-static-fallback at least.

**Comment by zdenham** [comment] 2024-06-25 05:44
Ah I see. So this seems like a capacitor specific issue that is incompatible with our approach. 

We generate a "fallback" page and fetch data client side. If capacitor enforces that all pages need to exist, you'll need to either

1. Generate all of your pages at build time using next.js [generateStaticParams](https://nextjs.org/docs/app/api-reference/functions/generate-static-params) or
2. If capacitor supports it, pass data as a query param e.g. /regions?objectId=[yourId]

I'd recommend option 2 if possible, because in a webview pretty urls aren't as important.

**Comment by zdenham** [comment] 2024-06-26 06:37
going to close this issue for now, as we likely won't be able to support capacitor with our current approach--please lmk if you end up getting this resolved

**Closed as completed by zdenham** 2024-06-26 06:37 UTC

**Comment by alanxp** [comment] 2024-06-26 06:40
As far as i know Sveltekit exports only 1 index.html and the rest of routes and pages are with javascript. So its basicly a SPA. I wonder if its possible to make a version that could change the hrefs to the fallback page so i wont get like the 404 error and fetched data thro the fallback (client side)
